### ISSUE TITLE
Issue for Rake task CI users: explicit version on did_you_mean dependency

### ISSUE THREAD

**Issue by olleolleolle** [zverok/yard-junk#21]
Situation: As a CI user of the Rake task, I can have gem activation issues due to explicit version demands. Example: https://github.com/cucumber/aruba/issues/492#issuecomment-327731194

Resolution for that project: stop using it in CI. https://github.com/cucumber/aruba/pull/493

(This is a vague description of the issue, but I wanted it saved, here, so that we can deal with it together.)

**Comment by zverok** [comment]
Oh damn. I've already had a fight with the bundled gem, but probably solved the problem in a wrong way :(
On it.

**Comment by zverok** [comment]
Seems that simplified version of setting up the dependency did the trick: https://travis-ci.org/zverok/yard-junk

Do we have any way of test it against aruba's Travis?..

BTW, I've also noticed aruba supports Rubies since 1.9.3. Till today, yard-junk supported only Ruby >= 2.3.0, but I added 2.1 and 2.2 in master. 

Not sure about 2.0 and 1.9.3 -- it is possible to support them, probably... But I don't really want to :)

**Comment by zverok** [comment]
(Though, in fact, it doesn't look as a really important task to support all Ruby versions, as docs could be checked only on one of them.)

**Comment by olleolleolle** [comment]
>  docs could be checked only on one

This is a good point. This could be the way forward that we teach.

It could be worth exampling this with a Travis CI config snippet which uses a `matrix` line which uses `rvm: 2.4.1` and does a `script: bundle exec rake yard:junk`

**Comment by zverok** [comment]
So, my CI is green now... 
Wanna me to release new gem version?

**Comment by olleolleolle** [comment]
@zverok Would be great!

**Comment by zverok** [comment]
Done!

**Comment by olleolleolle** [comment]
I will close this as fixed and open another issue if it appears.

**Comment by zverok** [comment]
Hey. Just notifying: I've did the [SECOND](https://github.com/zverok/yard-junk/commit/3de31fa9f9674b1b74b136fb4559e7f28b37b852) fix of the problem, now hopefully the right way. Released with 0.0.5
